# Name your workflow.
name: Deploy DocC
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      # Must be set to this for deploying to GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-15
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4
      - name: Build DocC
        run: |
          xcodebuild docbuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -scheme Xogot \
            -derivedDataPath /tmp/docbuild \
            -destination 'generic/platform=macOS';
          rm Documentation.docc/Documentation.md;
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug/Xogot.doccarchive \
            --hosting-base-path / \
            --output-path docs;
          $(xcrun --find docc) convert \
            --experimental-enable-custom-templates \
            --hosting-base-path / \
            --output-path /tmp/docs Documentation.docc;
          find docs -name index.html -exec cp /tmp/docs/index.html {} \;
          for file in $(find . -name '*.js'); do
            count=$(grep -o 'e\.currentLanguage\.name' "$file" | wc -l)
            if [ "$count" -gt 0 ]; then
              sed -i '' 's/e\.currentLanguage\.name/"GDScript"/g' "$file"
              echo "[$file] Replaced $count occurrences"
            fi
          done

          mv Documentation.docc/Resources/favicon.* docs;
          cp Documentation.docc/Resources/*.css docs/css;
          cp Documentation.docc/Resources/*.js docs/js;
          cp Documentation.docc/Resources/xogot-logo-white.png docs/img;
          cp Documentation.docc/Resources/xogot-logo-black.png docs/img;
          echo "<script>window.location.href += \"/documentation/xogot\"</script>" > docs/index.html;
          (cd docs; find . -name '*html' | sed -e 's,^.,https://docs.xogot.com,') > docs/sitemap.txt
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload only docs directory
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
